FROM node:22-alpine AS base
WORKDIR /app

ARG NODE_PORT
ENV NODE_PORT=${NODE_PORT:-5173}

RUN apk add --no-cache curl libc6-compat git

RUN corepack enable
RUN corepack prepare pnpm@10.17.1 --activate

COPY package*.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 5173


FROM base AS dev

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD curl -f http://localhost:${NODE_PORT} || exit 1

CMD ["sh", "-c", "\
  echo 'Starting development server...' && \
  pnpm run dev --host 0.0.0.0 --port ${NODE_PORT} \
  "]
