services:
  app:
    build:
      context: .
      dockerfile: .docker/node/Dockerfile.prod
      args:
        - NODE_ENV=production
    container_name: app-prod
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '${NODE_PORT:-5173}:80'
    environment:
      - NODE_ENV=production
      - NODE_PORT=${NODE_PORT:-5173}
      - API_URL=${API_URL}
      - APP_NAME=${APP_NAME}
      - VITE_ENABLE_DEVTOOLS=${VITE_ENABLE_DEVTOOLS}
      - VITE_ENABLE_MOCK_API=${VITE_ENABLE_MOCK_API}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    networks:
      - eventdev-prod-network

networks:
  eventdev-prod-network:
    external: true
